apiVersion: v1
kind: Service
metadata:
    name: currency-conversion-app
    labels:
        app: currency-conversion-app
spec:
    type: NodePort
    ports:
        - port: 8100
          targetPort: 8100
          nodePort: 30289
    selector:
        app: currency-conversion-app