apiVersion: apps/v1
kind: Deployment
metadata:
    name: mywebserver
    labels:
        app: httpd
spec:
    replicas: 10
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 3
            maxUnavailable: 4
    selector:
        matchLabels:
            app: httpd
    template:
        metadata:
            labels:
                app: httpd
        spec:
            containers:
                - name: myhttpd
                  image: httpd
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: demovol
                        mountPath: /data
                      - name: my-config-vol
                        mountPath: /etc/config
                      - name: my-secret
                        mountPath: /etc/mysecrets
                      - name: my-pvc
                        mountPath: /data/clustervol
            volumes:
                - name: demovol
                  hostPath:
                      path: /data
                      type: Directory
                - name: my-config-vol
                  configMap:
                      name: demo-configmap
                - name: my-secret
                  secret:
                      secretName: demo-secret
                - name: my-pvc
                  persistentVolumeClaim:
                      claimName: demo-pvc