spring:
  application:
    name: currency-conversion
  zipkin:
    base-url: http://192.168.99.105:9411/
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8100
  servlet:
    context-path: /currency-conversion/
# Register with Eureka Naming Server
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.105:8761/eureka
