spring:
  application:
    name: currency-conversion
server:
  port: 8100
  servlet:
    context-path: /currency-conversion/
# Register with Eureka Naming Server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
