# application name
spring:
  application:
    name: naming-server

#port
server:
  port: 8761

# Eureka server should not register with itself
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
