spring:
  application:
    name: currency-exchange
#data source
  datasource:
#    url: jdbc:mysql://localhost:3306/testdb
# docker mysql connection
    url: jdbc:mysql://docker-mysql:3306/testdb
    username: root
    password: pratap
  jpa:
    show-sql: true
  zipkin:
    base-url: http://192.168.99.100:9411/
    #sender:
    #  type: rabbit
  #Trace every request in dev environment probability: 1.0, eg: 0.05 trace only 5% of request
  sleuth:
    sampler:
      probability: 1.0
server:
  servlet:
    context-path: /currency-exchange/
  port: 8000
# Register with Eureka Naming Server
#eureka:
 # client:
  #  service-url:
   #   defaultZone: http://192.168.99.100:8761/eureka
#Resilience4j
resilience4j:
  retry:
    instances:
      sample-api:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
# kubernetes
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
